### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by corelon** [richrd/suplemon#101]
Hello I tried installing suplemon on Cygwin and native windows 7 and in the latter case I get a stacktrace for curses not being there. I installed unicurses but I still having the same issue. In cygwin it installs fine but within the editor I get an error saying
0 [main] python3.4m 9024 child_info_fork::abort: address space needed by 'grp.cpython-34m.dll' (0x3F0000) is already occupied
Any plans on supporting windows natively?

**Comment by richrd** [comment]
Cool to hear you've been trying it on Windows. Unfortunately I don't have a Windows machine to test at the moment. Originally I haven't planned to support Windows, since I feel the command line isn't used that much (correct me if I'm wrong). Suplemon was mainly created to make editing on remote unix servers easy and powerful. I'm interested in what kind of use case you have on Windows?

If Python 3 and curses can run on Windows, Suplemon *should* work too. The error looks like it might not be related to Suplemon directly. Can you get normal Python 3 scripts to run properly?

**Comment by twolfson** [comment]
As a heads up, Microsoft provides test VMs for Internet Explorer. I have found them as great sources for testing programs on Windows as well =)

https://dev.modern.ie/tools/vms/linux/

Native Windows isn't too friendly so I recommend using Chocolatey and Cmder:

https://chocolatey.org/

http://cmder.net/

There's also a CI for Windows: AppVeyor

http://www.appveyor.com/

**Comment by richrd** [comment]
Closing this since the initial error doesn't seem specific to Suplemon, and unfortunately I'm not planning native to do Windows support.
