### ISSUE TITLE
Hello | Plugins dir

### ISSUE THREAD

**Issue by Alexey-T** [richrd/suplemon#114]
Nice work on Python editor..
1) I read about plugins dir (at root of github) and cannot find plugins dir to see about plugins (I need not GH?)
2)I make CudaText editor. some part in Python. maybe want to port some of Suplemon code but cannot see plugins

**Comment by richrd** [comment]
Thanks!
1) The 'plugins' or modules can be found here. https://github.com/richrd/suplemon/tree/master/suplemon/modules They're pretty basic at the moment since I haven't finalized the module API yet. 
2) You can port anything you like as long as you follow the MIT license.

CudaText looks pretty nice :)

**Comment by Alexey-T** [comment]
Maybe you know man,who can help to write Ftp plugin (for $).

**Comment by richrd** [comment]
Sorry, I don't have a suitable contact.
