### ISSUE TITLE
Question: Should yes/no promts like exit need pressing enter to accept the value.

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#122]
Or should they automatically be activated when either y or n is pressed? I'm interested in hearing any ideas or views of others, thanks!

**Comment by twolfson** [comment]
For reference from what other tools do:

- `vi` doesn't allow exit on `:q` (error message is `E37: No write since last change (add ! to override)`)
- `nano` prompts only when buffer is dirty (e.g. new unsaved content)
    - This prompt exits immediately when `y` is pressed

When using `nano`, the behavior feels right since it's an editor not a REPL. We are prob fine to not require "enter" for Y/N prompts

**Comment by richrd** [comment]
I agree. Let's do it without requiring enter. Seems like an extra step after the decision has already been made.
