### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by alexmigf** [richrd/suplemon#140]
I'm new to bash code editors but i think this one has impressed me.

I have 2 problems, shouldn't be bugs, to setup it properly on my Fedora Worskstation.

1) Can't use CTRL+Page Up to move between open files, nothing happens.
2) I'm facing this error: suplemon.config - INFO - Failed to load config file '/home/alexandre/.config/suplemon/suplemon-config.json'.

Congrats for this piece of software, it's really great for Nano lovers.

**Comment by richrd** [comment]
Hi, are you still having problem 1? The key handling should be working properly in the latest version. If not I'll do my best to fix it. Let me know in wich environment you're running suplemon in (what shell and are you using it over SSH?).

Problem 2 doesn't really matter, suplemon is just saying that no custom configuration was loaded (the file doesn't exist if you haven't created it). It will use the default configuration and everything should work with that.

Hopefully suplemon is working well otherwise, and let me know if you need help :)

**Comment by alexmigf** [comment]
Hi,

Everything is fine, to be honest i didn't read the documentation before posting the issue, then i read and configured everything.

I'm really impressed and i will be using it has my main editor. I like nano and this is terrific.

Congratz and keep improving it, i will be using it and i will suggest features/ideas if are appropriated :)

**Comment by richrd** [comment]
Hi again!

Great to hear, and thanks for the motivating support! :)

I'll definitely continue working on suplemon, and any features and ideas are highly appreciated.
