### ISSUE TITLE
Pygments By Default

### ISSUE THREAD

**Issue by indolering** [richrd/suplemon#166]
Syntax highlighting should be included and enabled by default.

**Comment by richrd** [comment]
That would be nice but I'd like to avoid forcing Suplemon to depend on any non standard libraries. Any idea if we could auto-install it if it's available, but ignore it if it's not?

**Comment by richrd** [comment]
Found this, looks useful: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by indolering** [comment]
I'm not a Python programmer nor do I have any experience with your rather strange assortment of dependency managers.

**Comment by richrd** [comment]
Maybe I should just add the following to `setup.py`
```
      install_requires=[
          "pygments"
      ],
```
@twolfson Is there a better way of doing this? I'd like it to ignore the dependency if it's not found, but I guess that won't be a problem since pygments is on pypi. What about when people simply run `python3 setup.py install` ?

**Comment by indolering** [comment]
> What about when people simply run python3 setup.py install ?

You could just output text stating that if they want syntax highlighting they must install pygments as well, or even offer to install it for them.

**Comment by twolfson** [comment]
@richrd Shooting from the hip I would say that optional dependencies sounds reasonable for what you want. People should be able to do:

```
pip3 install suplemon[all]
```

I used `[all]` since I don't know if you can have multiple install requisites specified. If you need a point of reference, `splinter` uses `extra_requires` for installing different browser engines:

https://github.com/cobrateam/splinter/blob/0.7.4/setup.py#L27-L30

https://splinter.readthedocs.io/en/latest/drivers/flask.html

I'm not familiar enough with what would happen to a `python3 setup.py install` but I suggest try it and find out =P

@indolering It's already documented that `pygments` must be installed for syntax highlighting (including instructions):

https://github.com/richrd/suplemon/tree/v0.1.44#optional-dependencies

https://github.com/richrd/suplemon/blob/v0.1.44/docs/optional-dependencies.md

**Comment by richrd** [comment]
Thanks for the help!

Looks like `python3 setup.py install` will download & install pygments even if pip isn't installed. It makes me feel like maybe pygments could even be a required dependency.

Suplemon will install even if pygments can't be installed (e.g. no network connection), but unfortunately it won't run.
```pkg_resources.DistributionNotFound: The 'pygments' distribution was not found and is required by Suplemon```

**Comment by MrDowntempo** [comment]
I'll play devil's advocate on this one. Syntax highlighting if wonderful, 
but it's not necessary. If you're only using the editor to tweak basic 
config files from time to time or during setup, but not doing any real 
coding with it, it's certainly not needed. Nano would be the prime example 
of a useful editor without syntax highlighting support.

I will fully admit however that I am using suplemon with pygments though. 
Just pointing out that having pygments as only an optional dependency isn't 
horrible. :)

**Comment by twolfson** [comment]
For what it's worth, `nano` supports syntax highlighting and even has files bundled for them but they are disabled by default:

http://askubuntu.com/questions/90013/how-do-i-enable-syntax-highlighting-in-nano

**Comment by MrDowntempo** [comment]
Ok, that's cool, I didn't know that :)

**Comment by richrd** [comment]
Thanks for the input @MrDowntempo @twolfson :+1: Lets go for the optional dependency. It's nice that pygment's is on pypi, because we can just use the same command for installing on all platforms. (No need to instruct the user to install a distro specific package)

@MrDowntempo regarding what you said about syntax highlighting: what do you think about the (greatly inferior) line based highlighting provided by default? Did it feel weird or was it nice to have at least some colors before installing pygments?

**Comment by indolering** [comment]
> I'll play devil's advocate on this one. Syntax highlighting if wonderful, but it's not necessary.

This is a very neckbeard argument, I even saw a config file that disabled syntax highlighting by default because it "distracts" users.  Syntax highlighting reduces cognitive load and helps catch mistakes (especially for those of us who are not natural programmers).

> If you're only using the editor to tweak basic config files from time to time or during setup, but not doing any real coding with it, it's certainly not needed. Nano would be the prime example of a useful editor without syntax highlighting support. ... Just pointing out that having pygments as only an optional dependency isn't horrible. :)

Argh, I'm a usability engineer and you are killing my inner child.  You don't *need* syntax highlighting to modify a text file, but then why don't we just use `nano`?

> I will fully admit however that I am using suplemon with pygments though.

Shouldn't we give users the best configuration by default?

> For what it's worth, nano supports syntax highlighting and even has files bundled for them but they are disabled by default:

Yes, Bash and Nano and everyone else disables syntax highlighting by default, *and that is a mistake*.  For me, Suplemon differentiates itself from Nano because it is easier to use and syntax highlighting significantly enhances usability.  It's 2016: can we please let usability take priority in FOSS software?

This really should be enabled by default, with disabling it available as a config option during install.  Everyone has internet, no one is going to download Suplemon to a floppy disk and sneakernet it across the server room.  If someone needs to install it without any dependencies, then give them a link to some documentation on how to do it.

**Comment by MrDowntempo** [comment]
I can't really argue your points because I mostly agree with them. (Not 
everyone has internet though) As I said, I was just playing devil's 
advocate. I could argue that pygments is more bloat for supper minimal 
installs, but honestly if someone is that tight on space and performance, 
they're likely not using a Python coded text editor like suplemon in that 
use case either. And again, I use it with Pygments regardless of weather 
that becomes required or not. Your arguments about providing the best 
defaults in this case are in my view valid. Suplemon does work without 
pygments though, so allowing it to be installed without it as an option for 
people with some weird use case I can't imagine right now seems OK too. I 
guess in a perfect world pygments would be installed by default but 
suplemon would still work with pygments uninstalled? Would making it a 
required dependency make suplemon easier to maintain? And let me just say, 
I'm only a user and not enough of a programmer to provide really helpful 
opinions, I just am really enamored by this project :) I'm cool with 
whatever route Richard chooses!

**Comment by MrDowntempo** [comment]
Sorry I can't answer that, Richard. I installed pygments from the get go 
and didn't use suplemon without it. :(

**Comment by richrd** [comment]
I've decided to have pygments install by default when installing the package. Pygments is available on pypi, so it shouldn't be a problem. Even if it can't be installed running suplemon from source will still work fine. Hopefully this is the best of both worlds.

**Comment by richrd** [comment]
Wow, this took a long time, way too long. I added pygments as a dependency in the latest release. :tada:
