### ISSUE TITLE
xfce4-terminal: keyboard input of non-english characters doesn't work

### ISSUE THREAD

**Issue by d9k** [richrd/suplemon#172]
xubuntu 16.04, xfce4-terminal 0.6.3, suplemon 0.1.56

Non-english letters (russsian language) already existent in file are displayed, but when I try to input non-english characters with keyboard, nothing happens, cursor doesn't move. File can be saved, new non-english characters don't go to file.

Nano editor handles non-english charracters perfectly fine.

How can I debug the issue?

**Comment by richrd** [comment]
Hi!

Thanks for reporting this. What Python version are you using? If it's not Python 3 special characters aren't supported (I know that sucks but that's how the curses lib works 😞  ) If you're using Python 3.4 or higher it's probably a bug in suplemon.

**Comment by d9k** [comment]
I installed suplemon from cloned repository by `sudo python3 setup.py install` command.

```
% python3 --version
Python 3.5.2
```

**Comment by richrd** [comment]
I did some testing, and found the bug. For some reason the key code is a string for some characters and an int for others. It's a bit messy since curses is so weird and I'm trying to support both python versions as well as possible.

I pushed the fix to the dev branch. Could you verify it's working correctly? If it's fine I recommend using the dev branch until I get a new version released. The dev branch is usually very stable as I avoid pushing any work-in-progress code to it.

I hope this helps!

**Comment by d9k** [comment]
Awesome, @richrd, you totally fixed it! :sparkles: Thanks a lot!
