### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by xduino11** [richrd/suplemon#179]
Wouldn't it be kind of nifty to use sublime 2/3's API specs, then all those plugs would be available (aren't they in python mostly?)

**Comment by ozra** [comment]
Oops, wrong user - this is my common one.

**Comment by richrd** [comment]
This is something I'd like to get done, because suplemon really needs a solid API one way or another. There's been some discussion in #50 about that and consistency with sublime text in general. Other major things like not having selections/regions should be fixed too. To get everything implemented properly I'm rewriting the core of suplemon. 

Some details about what's coming up are laid out in #161 and #176. Anyway, I hope you enjoy the current version of suplemon. Let me know if you have any issues :)

**Comment by ozra** [comment]
I tried it a little while, but felt a bit limited, so I'm continuing with vim and sublime side by side for a while, I'll revisit you editor again I'm sure - it seems very promising!!

**Comment by richrd** [comment]
Thanks for trying it! :) It'll be worth trying again when I get through with the refactoring. Were there some specific things that you missed the most (like selections, auto-complete dropdown, split screen, file tree, something else)? I'd really like feedback to help me focus on the most important features/use cases.

**Comment by ozra** [comment]
I think some of it related simply to common selection with shift-arrows which is likely due to console limitations, and thus not much to do about. But yeah - auto-complete popup/dropdown list, file browsing and split - you nailed them!

**Comment by richrd** [comment]
Closing as this is an obvious goal of the rewrite.
