### ISSUE TITLE
Invalid indentation on paste

### ISSUE THREAD

**Issue by bagage** [richrd/suplemon#201]
It's something I already saw this `nano`, but it looks suplemon is pasting some content incorrectly.

See steps to reproduce:

1. Copy the following content `ctrl-c`:

```
level0
    level1
    level1
level0
```

2. Open somefile `suplemon somefile` and paste it `ctrl-v`

### Expected behavior
The content is pasted as is.

### Actual behavior

2 last lines are indented incorrectly:
![image](https://user-images.githubusercontent.com/1451988/31820956-a5a2b8a8-b5a3-11e7-8a2c-05c99b50061b.png)

If you copy these directly in the terminal for instance, there are properly indented.

**Comment by richrd** [comment]
Are you sure you're not using <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>v</kbd>? If you are the problem happens because of the auto indent feature. Pasting text that way into a terminal is the same as typing it by hand, and every new line is interpreted as <kbd>enter<kbd> and causes the auto indent to kick in.

If you are using suplemon locally you could use the system clipboard integration (see here: https://github.com/richrd/suplemon#optional-dependencies) If your using it via SSH the integration won't work so you'll just need to disable auto indent in the settings before pasting. There should probably be a paste mode or something like that to avoid having to mess with the settings every time.

**Comment by bagage** [comment]
I'm running under MacOSX / iterm2. The problem was when I used `cmd+V`, but if I use `ctrl+v` instead, it works as expected. 
I didn't knew that both are available, but since `ctrl+v` does the trick I think it's OK to close the issue. Thanks!

**Comment by richrd** [comment]
Great! I'll add a new issue for paste mode, because this is still a problem if using suplemon on a server via SSH.
