### ISSUE TITLE
Cursors not working over SSH with PuTTY and how to leave help?

### ISSUE THREAD

**Issue by Zeokat** [richrd/suplemon#243]
I'm trying to use Suplemon over a SSH session with PuTTY (from windows machine) and can't place cursors at all with combination `alt` + `arrow`.

Also, when i use `ctrl` + `h` to get help screen, ¿how can i leave this? All that i can do is use `ctrl` + `q` to close the program.

**Comment by MultifokalHirn** [comment]
+1
does not work with openssh from macOS to Ubuntu 18.04 (suplemon is installed in Ubuntu)

**Comment by richrd** [comment]
I need to look into that. @MultifokalHirn do the keys work when you run suplemon locally?

@Zeokat the help can be closed just like any tab, with <kbd>CTRL</kbd>+<kbd>W</kbd>. It's written in the help page :)

**Comment by MultifokalHirn** [comment]
yes they do work locally, sorry for the late reply.

**Comment by richrd** [comment]
Which terminal are you using on Mac @MultifokalHirn ?

**Comment by caph1993** [comment]
I can confirm the issue from Linux to Linux, however the issue is merely related to PuTTY. If you use SSH in any other terminal, the alt+keys combinations will work. You can even try with xterm, which is used by PuTTY under the hood.

PuTTY has several problems with keybindings, and users try to solve them separately with keymappings and other workarounds. Some of them are impossible to fix. I tried some hours before giving up using some of the hints mentioned in the links below. You can try further, but I definitely recommend you to quit using PuTTY if you are using it just for SSH.

- [How to fix Arrows](https://stackoverflow.com/questions/14837248/arrow-keys-in-putty-returning-a-d-b-instead-of-moving-the-cursor)
- [How to fix Home-End-PgUp-PgDown](https://superuser.com/questions/94436/how-to-configure-putty-so-that-home-end-pgup-pgdn-work-properly-in-bash)
- [How to fix Ctrl+Arrows](https://superuser.com/questions/103069/putty-ssh-ctrlcursor-keys-dont-work-skip-to-previous-next-word)
- [Shift+Arrows simply does not work. It's a bug.](https://superuser.com/questions/1223266/shift-arrow-keys-working-in-kitty-but-not-putty-for-nested-tmux-configuration)
- [Map Ctrl+B+Arrows to Alt+Arrows](https://superuser.com/questions/1271409/putty-vim-alt-keys).
