### ISSUE TITLE
Still maintained

### ISSUE THREAD

**Issue by Pulgovisk** [richrd/suplemon#245]
This project is dead or it still maintained?

**Comment by richrd** [comment]
Good question! Unfortunately the current version isn't actively developed or maintained. I will sometimes add bug fixes and possibly even features.

Now my main focus in this project is rewriting it from scratch so that features such as selections can be implemented. Even though the current version is usable there are a lot of shortcomings and it's hard implement new major features. There are two branches for the rewrite but unfortunately neither of them are even close to usable now due to a lack of time.
