### ISSUE TITLE
Optimize performance on low end devices

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#94]
On lower performance devices like the RaspberryPi Suplemon runs slowly.
Possibbly because:
 * All files are checked for changes after each keypress (this seems to be one of the most expensive operations, disabling it made a substantial difference)
 * ~~The entire screen is repainted after each keypress~~
 * Syntax highlighting isn't cached (although disabling it didn't make much difference) 
 * Other expensive processing during the main loop (?)

**Comment by trylle** [comment]
I'm getting excessive flickering in the viewer on both urxvt and xterm. This appears to be due to the terminal getting fully cleared and then refreshed. Also worth noting that this is on an pretty beefy machine (i7-4790k) running Arch and i3.

If I change viewer.py:306 from a clear to erase, then the flickering goes away. See http://lists.gnu.org/archive/html/bug-ncurses/2014-01/msg00007.html.

Butchered GIF from imagemagick demonstrating the issue and behavior after fix:
![Viewer flickering](http://virtual.metapathy.com/~frits/suplemon.gif)

[original source](http://virtual.metapathy.com/~frits/suplemon.mkv)

**Comment by richrd** [comment]
Wow, your flickering looks horrible, I'm really sorry about that. Thanks for reporting, it makes me want to raise the priority on this issue. :+1: 

I tried to fix the flickering some time ago, and was able to get good results (on ubuntu terminal and konsole) by replacing many `erase` calls with `clear`. I guess I missed that one in `viewer.py`. I'll test this out and push a fix ASAP.

Thanks again, the user experience is a top priority for me, and that crazy flickering is unacceptable.
Later I'm aiming to improve the UI by only rendering stuff that has actually changed, but that requires a lot more work. On the other hand curses seems to do that pretty well by itself.

**Comment by richrd** [comment]
Hi again. I changed `clear` to `erase` in the dev branch like you suggested. Let me know how it works. For me it didn't change anything, since I don't have flickering anyway. I hope it helps. If it fixes the flickering I'll push out a new version with the fix.

**Comment by trylle** [comment]
Thanks! Running the latest version on dev branch seems to solve the problem for me.

Curious that you don't see this behavior. So, I just tested both versions on a pure console terminal, and, again, I could see similar flickering there on the old version, but none in the new one.

Just want to note that the GIF conversion rather exaggerates the effect, though. The video file I linked to below is much more representative, since you seemed so anxious about it. :)

For me (on my beefy machine), I'm not sure I see a huge benefit to partial updates. It might be useful to have it only update the line it's currently working on, but I probably wouldn't notice a great improvement as long as curses is properly updating the terminal with only the stuff that actually changed (which with the latest fix, it seems to do). With slower machines, I can certainly see it being a factor.

However, I was wondering a bit if an easy win to improve the responsiveness of the editor, would be to read and handle all available input events before doing a refresh, because I can definitely notice that pasting text into the terminal using shift-insert (rather than ^V) is really slow, since it seems to be inserting one character and refreshing the viewer for each character.

**Comment by richrd** [comment]
Thanks for the note about the GIF. I didn't have a change to view the video until now. On some systems I have had the same level of flickering as in your video, just not on my setup. Anyway good that it's ok now. I'll be pushing a new version out to `master` soon. Thanks again!

I'll look into the shift-insert problem when I have time. (I wish pasting over SSH was as good as with e.g. nano) It might be hard, since curses only returns a single key at a time, and there doesn't seem to be a way of knowing if more input is available. I'd probably have check for input and have a timer that renders the input after 50ms of inactivity. (or something like that).

**Comment by trylle** [comment]
You can tell curses to run in non-blocking mode (nodelay). I made a quick and dirty proof-of-concept in e3d916443435bdfc2d9ebca3494ccd208dae8b96. This allows me to shift-insert pretty fast, but it probably breaks something. :)

I think, ideally, there should be clear separation between input handling and rendering in the code (this would make the block_rendering variable unnecessary).

**Comment by richrd** [comment]
Wow, great! I'll have to look at it more closely and test it, but it looks good! It's great to get good contributions and I really appreciate that. Thanks :+1:

I totally agree with input/rendering separation. There's a few things I would like to refactor (this included), but I think this could be merged for now (after testing). :)

**Comment by richrd** [comment]
Hi!

I finally got round to testing this and it seems to work great! :+1:
SSH pasting is way faster than before and the difference is amazing :)

I've got it in the current dev branch and hope to release it soon to the master branch.
Thanks again for your work!

**Comment by richrd** [comment]
Hi, optimizations have now been released in v0.1.50 and performance seems good enough. I'll close this for now but feel free to reopen if necessary.
